// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdCtEqgfxGQ3SiCS02c82dXZVwvvKEXw0',
    appId: '1:171151452115:web:87e47e4f2e03fe6b137126',
    messagingSenderId: '171151452115',
    projectId: 'second-attempt-becf1',
    authDomain: 'second-attempt-becf1.firebaseapp.com',
    storageBucket: 'second-attempt-becf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCMbeQLBSXTHZQ00-39hWmoiC6E0piEk',
    appId: '1:171151452115:android:d98d5a6104f3bece137126',
    messagingSenderId: '171151452115',
    projectId: 'second-attempt-becf1',
    storageBucket: 'second-attempt-becf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBh67pwsZljKk0zSw8nLSqdvzNhWRuok',
    appId: '1:171151452115:ios:1de7543c9ce1d647137126',
    messagingSenderId: '171151452115',
    projectId: 'second-attempt-becf1',
    storageBucket: 'second-attempt-becf1.appspot.com',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVBh67pwsZljKk0zSw8nLSqdvzNhWRuok',
    appId: '1:171151452115:ios:1de7543c9ce1d647137126',
    messagingSenderId: '171151452115',
    projectId: 'second-attempt-becf1',
    storageBucket: 'second-attempt-becf1.appspot.com',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdCtEqgfxGQ3SiCS02c82dXZVwvvKEXw0',
    appId: '1:171151452115:web:8a85bddeab9e555b137126',
    messagingSenderId: '171151452115',
    projectId: 'second-attempt-becf1',
    authDomain: 'second-attempt-becf1.firebaseapp.com',
    storageBucket: 'second-attempt-becf1.appspot.com',
  );

}